name: workflow for the nodejs application

on: 
  push: 
    branches:
      - 'feature/**'
      - 'main'
  pull_request:
    branches: 
      - 'feature/**'
      - 'main'

jobs:
  ci-cd:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: .
    steps: 
      - name: Checkout action to pull the code into the action runner
        uses: actions/checkout@v3
# this jobs is runing on the seld hosted runner   
      - name: checking the node envirment
        uses: actions/setup-node@v3
        with:
            node-version:: '18'
      - name: Install dependencies
        run: npm install --save-dev jest

      - name: Run tests with coverage
        run: npx jest --coverage --coverageDirectory=coverage

      - name: Upload the HTML coverage report
        uses: actions/upload-artifact@v4
        with:
         name: store-the-artifacts
         path: coverage
      - name: OWASP Dependency Check
        uses: dependency-check/dependency-check-action@v3
        with:
          project: node-github-action
          scan: .
          format: ALL
          out: dependency-check-report

      - name: Upload OWASP HTML report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report
      
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=node-github-action \
            -Dsonar.projectName=node-github-action \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN
#this commit contain that  the sonar user had granted  the necessay permssion update the system admanistator is chek now
# this commit contain that i have updatedx the sonar token the user which has fill permission right .
