name: workflow for the nodejs application

on: 
  push: 
    branches:
      - 'feature/**'
      - 'main'
  pull_request:
    branches: 
      - 'feature/**'

jobs:
  ci-cd:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: .
    steps: 
      - name: Checkout action to pull the code into the action runner
        uses: actions/checkout@v3
