name: workflow for the nodejs application

on: 
  push: 
    branches:
      - 'feature/**'
      - 'main'
  pull_request:
    branches: 
      - 'feature/**'
      - 'main'

jobs:
  ci-cd:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: .
    steps: 
      - name: Checkout action to pull the code into the action runner
        uses: actions/checkout@v3
# this jobs is runing on the seld hosted runner   
      - name: checking the node envirment
        uses: actions/setup-node@v3
        with:
            node-version:: '18'

      - name: to chek the vulnerabilties
        run: npm audit  --audit-level=high
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sudo npm install -g sonar-scanner
          sonar-scanner \
            -Dsonar.projectKey=node-github-action \
            -Dsonar.projectName=node-github-action \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN
